apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.server.web.service.name }}
spec:
  type: {{ .Values.server.web.service.type }}
  ports:
    - port: {{ .Values.server.web.service.port }}
  selector:
    app: {{ .Values.server.web.service.name }}