apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{ .Values.server.mariadb.service.name }}
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: {{ .Values.maria.pv.size }}
  hostPath:
    path: {{ .Values.maria.pv.path }}