apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: {{ .Values.server.mariadb.service.name }}
  name: {{ .Release.Name }}-{{ .Values.server.mariadb.service.name }}
  namespace: {{ .Values.server.mariadb.service.namespace }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Values.server.mariadb.service.name }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.server.mariadb.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.server.mariadb.service.name }}
    spec:
      containers:
        - image: mariadb:10.7
          imagePullPolicy: Always
          name: {{ .Values.server.mariadb.service.name }}
          resources: {}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb-secret
                  key: db
          ports:
            - containerPort: {{ .Values.server.mariadb.service.port }}
              name: mysql
          volumeMounts:
            - name:  {{ .Release.Name }}-{{ .Values.server.mariadb.service.name }}
              mountPath: /var/lib/mysql
          # readinessProbe:
          #     initialDelaySeconds: 20
          #     periodSeconds: 60
          #     exec:
          #       command:
          #         - "/bin/sh"
          #         - "-c"
          #         - "mysqladmin status -u root -p {{ .Values.server.mariadb.rootPassword }}"
      volumes:
        - name: {{ .Release.Name }}-{{ .Values.server.mariadb.service.name }}
          persistentVolumeClaim:
            claimName:  {{ .Release.Name }}-{{ .Values.server.mariadb.service.name }}
