apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.server.mariadb.service.name }}
spec:
  ports:
    - port: {{ .Values.server.mariadb.service.port }}
  selector:
    app: {{ .Values.server.mariadb.service.name }}