apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: deno-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - host: {{ .Values.server.web.service.host }}
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: {{ .Values.server.web.service.name }} 
                            port:
                                number: {{ .Values.server.web.service.port }}