apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  labels:
    app: {{ .Values.server.mariadb.service.name }}
  name: {{ .Values.server.mariadb.service.name }}
  namespace: {{ .Values.server.mariadb.service.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.server.mariadb.service.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.server.mariadb.service.name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.server.mariadb.service.maxSurge }}
      maxUnavailable: {{ .Values.server.mariadb.service.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.server.mariadb.service.name }}
    spec:
      containers:
        - image: mariadb:10.7
          imagePullPolicy: Always
          name: {{ .Values.server.mariadb.service.name }}
          resources: {}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: db
          ports:
            - containerPort: {{ .Values.server.mariadb.service.port }}
              name: mysql
          volumeMounts:
            - name: {{ .Values.server.mariadb.service.name }}
              mountPath: /var/lib/mysql
 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: logs
        - name: {{ .Values.server.mariadb.service.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.server.mariadb.service.name }}
 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.server.mariadb.service.name }}
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  capacity:
    storage: {{ .Values.maria.pv.size }}
  hostPath:
    path: {{ .Values.maria.pv.path }}
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.server.mariadb.service.name }}
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.maria.pvc.size }}
 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.mariadb.service.name }}
spec:
  ports:
    - port: {{ .Values.server.mariadb.service.port }}
  selector:
    app: {{ .Values.server.mariadb.service.name }}