apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mariadb-secret
type: kubernetes.io/basic-auth
stringData:
  password: {{ .Values.server.mariadb.password }}
  db: {{ .Values.server.mariadb.database }}